config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :users do
    resources :apartments, :only => [:index, :show, :edit, :destroy, :update] do
      resources :reviews
    end
    resources :circles, :only => [:show, :index]
    resources :messages, :only => [:index, :show, :new, :create, :destroy]
  end

  resources :memberships, :only => [:index, :destroy]

  get 'circles/add' => 'circles#add'

  get 'users/:user_id/personal' => 'users#personal', as: :personal

  resources :apartments, :circles

  get 'contact', to: 'welcome#contact', as: :contact
  get 'about', to: 'welcome#about', as: :about

  root 'welcome#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  # attr_accessible :subject, :body, :sender, :recepient, :read

  validates_presence_of :subject, :body, :recepient
  validates :subject, length: { minimum: 0, maximum: 35 }
  validates :body, length: { minimum: 0, maximum: 1000 }

  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @user = current_user
    @messages = Message.order("created_at desc")
    respond_to do |format|
      format.html
      format.json { render json: @messages }
    end
  end

  def show 
    @message = Message.find(params[:id])
    @user = current_user
    if (@user.email == @message.sender) || (@user.email == @message.recepient)
    else
      respond_to do |format|
        format.html { redirect_to :action => :index, notice: 'No message found' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params.merge({sender: current_user.email}))
    @message.sender = current_user.email
    @message.save
    # binding.pry
    respond_to do |format|
      if @message.save!
        format.html { redirect_to :action => :index, notice: 'Message has been sent.' }
        format.json { render json: @messages }
      else
        format.html { redirect_to :action => :new, notice: 'Error: Please try again.' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

 def message_params
    params.require(:message).permit(:recepient, :subject, :body)
  end

app/helpers/messages_helper.rb
module MessagesHelper
  def marked_as_read(message)
    if @message.read != 1 
      @message.read = 1
      @message.save 
    end
  end
end

app/views/messages/_form.html.erb
<%= form_for @message, :url => user_messages_path(current_user) do |form| %>

  <%= form.label :recepient %>
  <%= form.text_field :recepient %> <br><br>

  <%= form.label :subject %>
  <%= form.text_field :subject %> <br><br>

  <%= form.label :body %>
  <%= form.text_area :body %><br><br>
  <br>
  <%= form.submit 'Send message' %>

<% end %>

app/views/messages/_index.html.erb
<div class="allpagebackground">

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <img class="navbar-brand" src="/assets/roomiezlogo1.png" id = "rommiez_logo">
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
         <li><h4>&nbsp Welcome, <%= current_user.name %> </h4></li>
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Edit Profile', edit_user_path(current_user)%></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              </ul>     
            </li>
      </ul>

      <ul class="nav navbar-nav" id="myScrollspy" >
        <% if current_user.landlord %>
          <li><%= link_to 'Home', user_path(current_user)%></li>
          <li> <%= link_to 'My Apartments', user_apartments_path(current_user)%></li>
          <li> <%= link_to 'Add Apartment', new_apartment_path %> </li>
          <li class="dropdown" id="messageshover">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
                <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
                <li class="divider"></li>
                <li><a href="#">Trash</a></li>
            
        <% else %>
          <li> <%= link_to 'Home', user_path(current_user)%></li>
          <li><%= link_to "Find Apartments", apartments_path%></li>
          <li><%= link_to "Find Roommates", users_path%></li>
          <li class="dropdown" id="messageshover">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
                <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
                <li class="divider"></li>
                <li><a href="#">Trash</a></li>
              </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

<body class="pagebodybackground">
<div id="inboxbackground">
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#inbox" role="tab" data-toggle="tab">Inbox</a></li>
  <li><a href="#sent" role="tab" data-toggle="tab">Sent Messages</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">

  <div class="tab-pane active" id="inbox">
    <div id="inboxMessages">
      <h2>Inbox</h2>
       <button type="button" class="btn btn-default btn-sm">
        <%= link_to 'Create Message', new_user_message_path%>
        <span class="glyphicon glyphicon-pencil"></span> 
        </button> 
  
      <table class="table table-hover"> 
       <tr>
        <td>Subject</td>
        <td>From</td>
        <td>Date</td>
        <td>Functions</td>
      </tr>
     </table>
    <div id="messages">
      <%= render @messages %> 
    </div>
  </div>
  </div>

  <div class="tab-pane" id="sent">

  <div id="sentMessages">
    <h2>Sent Messages</h2>
    <table class="table table-hover">
      <tr>
        <td>Subject</td>
        <td>To</td>
        <td>Date</td>
         <td>Functions</td>

      </tr>
    </table>
    <div id="messages">
      <%= render 'messages/sent' %> 
    </div>
  </div>

</div>
</div>
</body>







  

  

app/views/messages/_message.html.erb
<link href="/assets/messages.css" rel="stylesheet">

<link href="/assets/bootstrap.css" rel="stylesheet">
<% if message.recepient == @user.email %>
<table class="table">
  <tr>
  
    <td>
      
       <% if message.read %>
         <span class="glyphicon glyphicon-ok"></span> 
         <% else %>
         <span class="glyphicon glyphicon-envelope"></span> 
      <% end %>
      <%= link_to message.subject, user_message_path(current_user, message) %>
    </td>
    <td>
      <%= message.sender %>
    </td>
    <td><%= message.created_at %></td>
    <td>
 
    <button type="button" class="btn btn-default btn-sm">
      <%= link_to 'Delete', user_message_path(current_user,message), method: :delete, data: { confirm: 'Are you sure?' } %>
     <span class="glyphicon glyphicon-trash"></span> 
    </button> 
    <button type="button" class="btn btn-default btn-sm">
      <%= link_to 'Reply', new_user_message_path%>
     <span class="glyphicon glyphicon-share-alt"></span> 
    </button>

  </td>
 
  </tr>
</table>
<% end %>

app/views/messages/_new.html.erb
<link href="/assets/messages.css" rel="stylesheet">
<body class="pagebodybackground">
<div id="newMessage">
  <h2>New message</h2>
  <%= render 'form' %>
  <%= link_to 'Back', user_messages_path(current_user) %>
</div>
</body>

app/views/messages/_sent.html.erb
<% @messages.each do |m| %>
<% if m.sender == @user.email %>
<table class="table">
  <tr>
    <td>
     
      <% if m.read %>
         <span class="glyphicon glyphicon-ok"></span> 
         <% else %>
         <span class="glyphicon glyphicon-envelope"></span> 

      <% end %>
       <%= link_to m.subject, user_message_path(current_user, m) %>
    </td>
    <td><%= m.recepient %></td>
    <td><%= m.created_at %></td>
    <td><button type="button" class="btn btn-default btn-sm">
      <%= link_to 'Delete', user_message_path(current_user,m), method: :delete, data: { confirm: 'Are you sure?' } %>
     <span class="glyphicon glyphicon-trash"></span> 
    </button> </td>
       

  </tr>
</table>
<% end %>
<% end %>

app/views/messages/_show.html.erb
<link href="/assets/messages.css" rel="stylesheet">
<body class="pagebodybackground">

<div id="readMessage">
<h3>Message</h3>
<h4> Subject : <%= @message.subject%> </h4>
<h4> From : <%= @message.sender%> </h4>
<h4> Date : <%= @message.created_at%> </h4>

<table class = "table">
  <tr> <td>
    <p><%= @message.body %></p>

   </td> <tr>
</table>


<%= link_to 'Back', user_messages_path(current_user) %>
<%= link_to 'Reply', new_user_message_path%>

</div>
</body>

app/views/messages/index.html.erb
<% if current_user %>
    <%= render 'messages/index' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>

app/views/messages/new.html.erb
<% if current_user %>
    <%= render 'messages/new' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>

app/views/messages/show.html.erb
<% if current_user %>
    <%= render 'messages/show' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>

<% marked_as_read(@message) %>