config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :users do
    resources :apartments, :only => [:index, :show, :edit, :destroy, :update] do
      resources :reviews
    end
    resources :circles, :only => [:show, :index]
    resources :messages, :only => [:index, :show, :new, :create, :destroy]
  end

  resources :memberships, :only => [:index, :destroy]

  get 'circles/add' => 'circles#add'

  get 'users/:user_id/personal' => 'users#personal', as: :personal

  resources :apartments, :circles

  get 'contact', to: 'welcome#contact', as: :contact
  get 'about', to: 'welcome#about', as: :about

  root 'welcome#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :apartments
	has_many :tasks, through: :apartments 
	has_many :memberships, :dependent => :destroy
	has_many :circles, through: :memberships
	has_many :messages
	has_many :reviews

	validates :name, presence: true

	#Does stuff that has to do with photo upload
	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/face.jpeg"
 	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

	

	def self.filter(query)
	  query.blank? ? User.all : User.where("name LIKE '%#{query}%' OR email LIKE '%#{query}%'")
	end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.filter(params[:q])
  end


  def show
    @user = User.find(params[:id])
    # Creates an array of the membership ids that tie the current user to their circles
    @memberships = []
    @user.circles.each do |c|
      c.memberships.each do |m|
	if @user.id == m.user_id.to_i
	  @memberships << m.id
	end
      end
    end
  end


  def edit
  end
  
  def personal
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :about, :age, :landlord, :photo_file_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="allpagebackground">
  <nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <img class="navbar-brand" src="/assets/roomiezlogo1.png" id = "rommiez_logo">
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li><h4> <%= link_to "Welcome #{current_user.name}", user_path(current_user) %> </h4></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
	<li><%= link_to 'Edit Profile', edit_user_registration_path(current_user)%></li>
	<li class="divider"></li>
	<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>     
      </li>

    </ul>
    <ul class="nav navbar-nav" id="myScrollspy" >
      <li> <%= link_to 'Home', user_path(current_user)%></li>
      <li class="currentpage"><%= link_to "Find Roommates", users_path%></li>
      <li><%= link_to "Find Apartments", apartments_path%></li>

      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
	<li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
	<li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
	<li class="divider"></li>
	<li><a href="#">Trash</a></li>
      </ul>     
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->

  </nav>
</div>

<body class="pagebodybackground">
  <div id="inboxbackground">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#tenant" role="tab" data-toggle="tab">Roomiez</a></li>
      <li><a href="#landlord" role="tab" data-toggle="tab">Landlords</a></li>
      <br>
      <%= form_tag users_path, :method => 'GET' do %>
	<%= text_field_tag 'q', params[:q] %>
	<%= submit_tag 'SEARCH' %>
      <% end %><br>
    </ul>
    <!-- Tab panes -->

    <div class="tab-content">
      <div class="tab-pane active" id="tenant">
	<table class="table">
	  <thead>
	    <tr>
	      <th>Picture</th>
	      <th>Name</th>
	      <th>Profile</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @users.each do |u| %>

	      <% if u.landlord == false && u != current_user && 
		(u.circles.empty? || !u.circles.first.users.include?(current_user)) %>
		<tr>
		  <% if u.photo_file_name %>
		    <td> <%= image_tag u.photo.url(:thumb) %> </td>
		  <% else %>
		    <td>  <img src="/assets/face.jpeg" id="facepic"></td>
		  <% end %>
		  <td><%= link_to u.name, "users/#{u.id}" %></td>
		  <!-- Button trigger modal -->
		  <td
		    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target=<%= "#myModal_#{u.id}" %> >
		      View Profile
		    </button>
		  </td>
		</tr>

		<!-- Modal -->
		<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" id=<%="myModal_#{u.id}"%>>
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<h3 class="modal-title" id="myModalLabel"> <strong><%= u.name %> </strong> </h3>
		      </div>
		      <div class="modal-body">
			<% if u.photo_file_name %>
			  <h4> <%= image_tag u.photo.url(:medium) %> </h4>
			<% end %>
			<h4> Email : <%= u.email %> </h4>
			<h4> Age : <%= u.age %> </h4>
			<h4> About : <%= u.about %> </h4>
		      </div>
		      <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<%= link_to "Add #{u.name}'s circle to your circle!", circles_add_path(:user_to_add => u.id), :class => "btn btn-default" %>
		      </div>
		    </div>
		  </div>
		</div>
	      <% end %>
	    <% end %>
	  </table>
	</div>
	<div class="tab-pane" id="landlord">
	  <table class="table">
	    <thead>
	      <tr>
		<th>Picture</th>
		<th>Name</th>
		<th>Profile</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @users.each do |u| %>
		<% if u.landlord == true && u != current_user %>
		  <tr>
		    <% if u.photo_file_name %>
		      <td> <%= image_tag u.photo.url(:thumb) %> </td>
		    <% else %>
		      <td>  <img src="/assets/face.jpeg" id="facepic"></td>
		    <% end %>
		    <td><%= link_to u.name, "users/#{u.id}" %></td>
		    <!-- Button trigger modal -->
		    <td
		      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target=<%= "#myModal_#{u.id}" %> >
			View Profile
		      </button>
		    </td>
		  </tr>
		  <!-- Modal -->
		  <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" id=<%="myModal_#{u.id}"%>>
		    <div class="modal-dialog">
		      <div class="modal-content">
			<div class="modal-header">
			  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			  <h3 class="modal-title" id="myModalLabel"> <strong><%= u.name %> </strong> </h3>
			</div>
			<div class="modal-body">
			  <h4> Email : <%= u.email %> </h4>
			  <h4> Age : <%= u.age %> </h4>
			  <h4> About : <%= u.about %> </h4>
			</div>
			<div class="modal-footer">
			  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			  <button type="button" class="btn btn-primary">Add landlord!</button>
			</div>
		      </div>
		    </div>
		  </div>
		<% end %>
	      <% end %>
	    </ul>
	  </div>
	</div>
      </div>
    </body>

app/views/users/personal.html.erb
<div class="allpagebackground">
  <nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <img class="navbar-brand" src="/assets/roomiezlogo1.png" id = "rommiez_logo">
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li><h4> <%= link_to "Welcome #{current_user.name}", user_path(current_user) %> </h4></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
	<li><%= link_to 'Edit Profile', edit_user_registration_path(current_user)%></li>
	<li class="divider"></li>
	<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>     
      </li>

    </ul>
    <!-- Nav bar if landlord and current_user -->
    <ul class="nav navbar-nav" id="myScrollspy" >
      <% if current_user.landlord %>
	<li class="currentpage"><%= link_to 'Home', user_path(current_user)%></li>
	<li> <%= link_to 'My Apartments', user_apartments_path(current_user)%></li>
	<li> <%= link_to 'Add Apartment', new_apartment_path %> </li>

	<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
	  <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
	  <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
	  <li class="divider"></li>
	  <li><a href="#">Trash</a></li>
	</ul>     
	</li>

	<!-- Nav bar for tenant and curernt_user -->
      <% elsif !current_user.landlord %>
	<li> <%= link_to 'Home', user_path(current_user)%></li>
	<li><%= link_to "Find Roommates", users_path%></li>
	<li><%= link_to "Find Apartments", apartments_path%></li>

	<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
	  <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
	  <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
	  <li class="divider"></li>
	  <li><a href="#">Trash</a></li>
	</ul>     
	</li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->  
  </nav>

  <div id="personal-info">
    <h3>Personal profile </h3>
    <ul>
      <% if current_user.photo_file_name %>
        <li><%= image_tag current_user.photo.url(:medium) %></li>
      <% else %>
        <li>  <img src="/assets/face.jpeg" id="facepic"></li>
      <% end %>
      <li><%="Name:  #{current_user.name}"%></li>
      <li><%="Age: #{current_user.age}"%></li>
      <li><%="Email: #{current_user.email}"%></li>
      <li><%="About me: #{current_user.about}"%></li>
      <li><%= link_to 'Edit profile', edit_user_registration_path(current_user)%></li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="allpagebackground">
  <nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <img class="navbar-brand" src="/assets/roomiezlogo1.png" id = "rommiez_logo">
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li><h4> <%= link_to "Welcome #{current_user.name}", personal_path(current_user) %> </h4></li>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
	<li><%= link_to 'Edit Profile', edit_user_registration_path(current_user)%></li>
	<li class="divider"></li>
	<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>     
      </li>

    </ul>
    <!-- Nav bar if landlord and current_user -->
    <ul class="nav navbar-nav" id="myScrollspy" >
      <% if current_user.landlord %>
	<li class="currentpage"><%= link_to 'Home', user_path(current_user)%></li>
	<li> <%= link_to 'My Apartments', user_apartments_path(current_user)%></li>
	<li> <%= link_to 'Add Apartment', new_apartment_path %> </li>

	<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
	  <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
	  <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
	  <li class="divider"></li>
	  <li><a href="#">Trash</a></li>
	</ul>     
	</li>

	<!-- Nav bar for tenant and curernt_user -->
      <% elsif !current_user.landlord %>
	<li class="currentpage"> <%= link_to 'Home', user_path(current_user)%></li>
	<li><%= link_to "Find Roommates", users_path%></li>
	<li><%= link_to "Find Apartments", apartments_path%></li>

	<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">
	  <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
	  <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
	  <li class="divider"></li>
	  <li><a href="#">Trash</a></li>
	</ul>     
	</li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->

  </nav>
</div>
<body class="pagebodybackground">
  <div class="jumbotron">
    <% if current_user == @user && current_user.circles.empty? %>
      <% if !current_user.landlord  %>
	<h1>Welcome to Roomiez!</h1>
	<p>
	Roomiez allows you to find and connect with roommates looking to live in the same location. Once you have joined a circle together, you and your roommate can embark on the apartment hunt together, ensuring that you live where you want, with the people you want to live with! Select "Find Roommates" to get started. 
	</p>
	<a class="btn btn-primary btn-lg" role="button" href="/users">Find Roommates</a>

      <% elsif current_user.landlord && current_user == @user %>
	<h1>Welcome to Roomiez!</h1>
	<p>
	As a landlord, Roomiez allows you to efficiently manage all of your apartments on a single platform. Seemlessly toggle through your various circles to collect rent payment online, manage maintenance requests, and easily interact with your tenants.
	</p>
	<a class="btn btn-primary btn-lg" role="button">Learn more</a>
      <% end %>
    <% elsif current_user == @user && @user.circles.any? %>
      <h2>Your Circle:</h2>
      <% @user.circles.each_with_index do |c, index| %>                 
	<% c.users.each do |user| %> 
	  <div class="row">
	    <div class="col-sm-6 col-md-4">
	      <div class="thumbnail">
		<% if @user.photo_file_name %>
		  <img><%= image_tag user.photo.url(:thumb) %></img>
		<% end %>
		<div class="caption">
		  <h3><%= user.name %> - 
		    <% if user.id == current_user.id %>
		      My Profile
		    <% elsif user.landlord %>
		      Landlord
		    <% else %>
		      Roomie
		    <% end %></h3>
		  <h4>
		    Age : <%= user.age %><br>
		    Email : <%=user.email%><br>
		    About : <%= user.about %><br> <br>

		    <button type="button" class="btn btn-info btn-sm">
		      <span class="glyphicon glyphicon-envelope"></span> 
		      <%= link_to "Message", new_user_message_path(current_user)%>
		    </button> 
		  </h4>
		</div>
	      </div>
	    </div>
	  <% end %>
	</div>

	<div class="tasks">
	  <div class="incomplete_tasks"
	    <h4>Tasks</h4>
	  </div>
	  <div class="complete_tasks"
	    <h4>Completed tasks</h4>
	  </div>
	</div>

	<% if c.apartment %>
	  <%= c.apartment.name %>
	  <%= link_to "Remove apartment", user_apartment_path(current_user, c.apartment, :remove_apt_from_circle => true), :method => :delete %>
	<% end %>

	<button type="button" class="btn btn-default" data-dismiss="modal">
	  <%= link_to "Leave circle", membership_path(@memberships[index]), :method => :delete %>
	</button>
      <% end %>
    <% elsif current_user != @user %>
      <ul>
	<% if current_user.photo_file_name %>
	  <li><%= image_tag current_user.photo.url(:medium) %></li>
	<% else %>
	  <li>  <img src="/assets/face.jpeg" id="facepic"></li>
	<% end %>
	<li><%= "#{@user.name}" %></li>
	<li><%= "#{@user.age}" %></li>
	<li><%= "#{@user.email}" %></li>
	<li><%= "#{@user.about}" %></li>
      </ul>
    <% end %>

    <br><br>
  </div>
</div>
  </body>