config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users
  resources :users do
    resources :apartments, :only => [:index, :show, :edit, :destroy, :update] do
      resources :reviews
    end
    resources :circles, :only => [:show, :index]
    resources :messages, :only => [:index, :show, :new, :create, :destroy]
  end

  resources :memberships, :only => [:index, :destroy]

  get 'circles/add' => 'circles#add'

  get 'users/:user_id/personal' => 'users#personal', as: :personal

  resources :apartments, :circles

  get 'contact', to: 'welcome#contact', as: :contact
  get 'about', to: 'welcome#about', as: :about

  root 'welcome#home'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user
  belongs_to :circle
  has_many :tasks

  #Does stuff that has to do with photo upload
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/face.jpeg"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

    def self.filter(query)
      query.blank? ? Apartment.all : Apartment.where("street_address LIKE '%#{query}%' OR city LIKE '%#{query}%' OR state LIKE '%#{query}%'")
    end

  # change the apt.circle_id to current cricle
  def add_to_circle(current_user)
    # if usert has a circle then he/she can add an apt
    if current_user.memberships.any?
      self.circle_id = current_user.memberships.first.circle_id
      self.occupied = true
      self.save
      # add apartment's landlord to circle
      # change landlord's circle_id to match current circle
      landlord = User.find(self.user_id)
      circle = Circle.find(self.circle_id)
      circle.users << landlord
    end
  end

  def remove_from_circle
    # Looks for the apartment's landlord
    landlord = User.find(self.user_id)
    # Looks for the landlord's membership
    membership = Membership.where(circle_id: self.circle_id, user_id: landlord.id).first
    membership.destroy
    # Delete circle's info from apt
    self.circle_id = nil
    self.occupied = nil
    self.save
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  def index
    # @apartments = Apartment.all
    if params[:user_id]
      @apartments = Apartment.where(:user_id => params[:user_id]).paginate(:per_page =>10, :page => params[:page])
    else
      @apartments = Apartment.filter(params[:q]).paginate(:per_page =>10, :page => params[:page])	
    end
  end

  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.user_id = current_user.id

    if @apartment.save
      redirect_to "/users/#{current_user.id}/apartments"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:add_to_circle]
      if @apartment.add_to_circle(current_user)
	redirect_to user_path(current_user), notice: 'Apartment was successfully added to circle!'				
      else
	redirect_to user_path(current_user), notice: 'You need a circle of friends before adding an apartment!'
      end
    else
      if @apartment.update(apartment_params)
	redirect_to "/users/#{current_user.id}/apartments", notice: 'Apartment was successfully updated.'
      else
	render :edit 
      end
    end
  end


  def show
    #@apartment = Apartment.find(params[:id])
    @apartments = Apartment.all

  end

  def destroy
    if params[:remove_apt_from_circle]
      if @apartment.remove_from_circle
	redirect_to user_path(current_user), notice: 'Apartment was successfully removed circle!'
      else
	redirect_to user_path(current_user), notice: 'Apartment could not be removed'
      end
    else
      @apartment.destroy
      redirect_to "/users/#{current_user.id}/apartments"
    end
  end


  private

  def set_apartment
    @apartment = Apartment.find(params[:id])
  end

  def apartment_params
    params.require(:apartment).permit(:name, :street_address, :occupied, :country, :zipcode, :user_id, :photo, :rent, :city, :state, :bedrooms, :bathrooms, :smoking, :pets, :furnished)
  end
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment, :multipart =>true) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="form_style">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>

  <br/><br/>

  <%= f.label :street_address %><br/>
  <%= f.text_field :street_address %>

  <br/><br/>

  <%= f.label :city %><br/>
  <%= f.text_field :city %>  

  <br/><br/>

  <%= f.label :state %><br/>
  <%= f.text_field :state %>  

  <br/><br/>

  <%= f.label :zipcode %><br/>
  <%= f.text_field :zipcode %>  

  <br/><br/>

  <%= f.label :country %><br/>
  <%= f.text_field :country %>

  <br/><br/>

  <%= f.label :rent %><br/>
  <%= f.text_field :rent %>

  <br/><br/>


  <%= f.label :bedrooms %><br/>
  <%= f.text_field :bedrooms %>

    <br/><br/>

  <%= f.label :bathrooms %><br/>
  <%= f.text_field :bathrooms %>
<div>
  <br/><br/>

  <%= f.label :occupied, "Please check box if the apartment is occupied: " %>
  <%= f.check_box :occupied %> 

    <br/><br/>

  <%= f.label :furnished, "Please check box if the apartment is furnished: " %>
  <%= f.check_box :furnished %> 

    <br/><br/>

  <%= f.label :smoking, "Please check box if the apartment allows smoking: " %>
  <%= f.check_box :smoking %> 

    <br/><br/>

  <%= f.label :pets, "Please check box if the apartment allows pets: " %>
  <%= f.check_box :pets %> 

  <br/><br/>
  
  <div class="field">
    <%= f.label "Upload a Photo : " %><br/>
    <%= f.file_field :photo %> <br/>
  </div>


  <div class="actions" id="submitbutton">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<body id="signinpage">

  <div class="border-form-div">

    <h1>Edit existing apartment</h1>


    <%= render 'form' %>

    <br/>

    <%= link_to "Go back", "/users/#{current_user.id}" %>

  </div>
</body>

app/views/apartments/index.html.erb
<div class="allpagebackground">
  <nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
        <img class="navbar-brand" src="/assets/roomiezlogo1.png" id = "rommiez_logo">
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        <ul class="nav navbar-nav navbar-right">
            <li><h4> <%= link_to "Welcome #{current_user.name}", user_path(current_user) %> </h4></li>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Edit Profile', edit_user_path(current_user)%></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
              </ul>     
            </li>
          
        </ul>
        <!-- Nav bar if landlord and current_user -->
        <ul class="nav navbar-nav" id="myScrollspy" >
          <% if current_user.landlord %>
            <li><%= link_to 'Home', user_path(current_user)%></li>
            <li class="currentpage"> <%= link_to 'My Apartments', user_apartments_path(current_user)%></li>
            <li> <%= link_to 'Add Apartment', new_apartment_path %> </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
                <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
                <li class="divider"></li>
                <li><a href="#">Trash</a></li>
              </ul>     
            </li>

          <!-- Nav bar for tenant and curernt_user -->
          <% elsif !current_user.landlord %>
              <li > <%= link_to 'Home', user_path(current_user)%></li>
              <li><%= link_to "Find Roommates", users_path%></li>
              <li class="currentpage"><%= link_to "Find Apartments", apartments_path%></li>
                            
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Inbox', user_messages_path(current_user)%></li>
                <li><%= link_to 'Create Message', new_user_message_path(current_user)%></li>
                <li class="divider"></li>
                <li><a href="#">Trash</a></li>
              </ul>     
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->

</nav>
</div>

<body class="pagebodybackground">
 <div id="inboxbackground">
<br> 
<p id="directiontext"> Search by location for an apartment : </p> <br>
<%= form_tag apartments_path, :method => 'GET' do %>
	<%= text_field_tag 'q', params[:q] %>
	<%= submit_tag 'SEARCH' %>
<% end %><br>


<table class="table table-hover">

    <thead>
        <tr>
            <th>Picture</th>
            <th>Name</th>
            <th>Rent Price</th>
            <th>Location</th>
            <th>Landlord</th>
            <th>Bedrooms</th>
            <th>Bathrooms</th>
            <th>Smoking</th>
            <th>Pets</th>
            <th>Occupied</th>
        </tr>
    </thead>

    <tbody>
        <% @apartments.each do |a| %>
        <tr>
            <td>
            <% if a.photo_file_name %>
            <%= image_tag a.photo.url(:thumb) %>
            <% end %>
            </td>
            <td>
            <%= link_to a.name, user_apartment_path(current_user, a) %> 
            </td>
            <td>
              <%= a.rent %>
            <td>
            <%= a.street_address %> <br/>
            <%= a.city %><br/>
            <%= a.state %><br/>
            <%= a.country %> <br/>
            <%= a.zipcode %> <br/>
            </td>
            <td>
              <% owner = User.find(a.user_id) %>
              <%= owner.name %>
            </td>
            <td>
              <%= a.bedrooms %>
            </td>
            <td>
              <%= a.bathrooms %>
            </td>
            <td>
              <% if a.smoking %>
                Yes
              <% else %>
                No
              <% end %>
            </td>
            <td>
              <% if a.pets %>
                Yes
              <% else %>
                No
              <% end %>
            </td>
            <td>
              <% if a.occupied %>
                Yes
              <% else %>
                No
              <% end %>
            </td>
        </tr>
        <% end %>
</table>


<%= will_paginate @posts %>
</div>
</body>

app/views/apartments/new.html.erb
<body id="apartmentpage">

  <div class="border-form-div">

    <h1>Add New Apartment : </h1>


    <%= render 'form' %>

    <br/>

    <%= link_to "Back", "/users/#{current_user.id}" %>

  </div>
</body>

app/views/apartments/show.html.erb
<body class="pagebodybackground">
  <div id="apartmentshow">

    <h1> <%= @apartment.name %> </h1>
    <% if !current_user.landlord %>
      <%= link_to "Add apartment to circle", user_apartment_path(current_user, @apartment, :add_to_circle => true), method: 'put' %>
    <% end %>
    <div>
      <%= image_tag @apartment.photo.url(:medium) %>
    </div>
    <br>
    <ul>
      <li><%= @apartment.rent %></li>
      <li><%= @apartment.street_address %></li>
      <li><%= @apartment.city %></li>
      <li><%= @apartment.state %></li>
      <li><%= @apartment.country %></li>
      <li><%= @apartment.zipcode %></li>
      <br>
      <li><%= @apartment.bedrooms %></li>
      <li><%= @apartment.bathrooms %></li>
      <br>
      <li> For more information contact : 
      <% owner = User.find(@apartment.user_id) %>
      <%= owner.name %> </li>
      <li>
      <% if @apartment.occupied %>
	The apartment is currently occupied.
      <% else %>
	The apartment is currently available.
      <% end %>
      </li>
      <li>
      <% if @apartment.smoking %>
	Smoking Allowed : Yes
      <% else %>
	Smoking Allowed : No
      <% end %>
      </li>
      <li>
      <% if @apartment.pets %>
	Pets Allowed : Yes
      <% else %>
	Pets Allowed : No
      <% end %>
      </li>
    </ul>

    <% if current_user.landlord %>
      <%= link_to "Edit", edit_user_apartment_path(current_user, @apartment) %>
      <%= link_to "Delete", "/users/#{current_user.id}/apartments/#{@apartment.id}", method: 'delete' %>
    <% end %>
    <br>

    <%= link_to "Review this apartment!", new_user_apartment_review_path(current_user, @apartment) %>
    <br>
    <h2> Reviews </h2>

    <table>
      <thead>
	<tr>
	  <th>Rating </th>
	  <th>Review</th>
	</tr>
      </thead>
      <% Review.all.each do |r| %>
	<% if r.apartment_id == @apartment.id %>
	  <tbody>
	    <td><%= r.rating %></td>
	    <td><%= r.body %></td>
	    <td><%= link_to "Edit", edit_user_apartment_review_path(current_user, @apartment, r.id) %></td>
	  </tbody>
	<% else %>
	  <p> There are no reviews of this apartment. </p>  
	<% end %>
      <% end %>
    </table>

    <br>
    <%= link_to 'Back', apartments_path %>

  </div>
</body>